name: udemy_flutter_sns
description: A new Flutter project.
 
publish_to: 'none' 
version: 1.0.0+1
 
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
    
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0 
  cloud_firestore: ^4.9.2 
  firebase_analytics: ^10.5.0 
  google_fonts: ^4.0.4
  pull_to_refresh: ^2.0.0
  image_cropper: ^4.0.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.13.0
  flash: ^3.0.5+1
  uuid: ^3.0.7
  image_picker: ^1.0.4
  flutter_svg: ^2.0.5
  firebase_storage: ^11.2.7 
  firebase_crashlytics: ^3.3.6 
  fluttertoast: ^8.0.9
  material_floating_search_bar_2: ^0.5.0
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  algolia: ^1.1.1
  freezed_annotation: ^2.1.0
 
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
 
dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
   intl: ^0.18.0-nullsafety.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env