name: udemy_flutter_sns
description: A new Flutter project.
 
publish_to: 'none' 
version: 1.0.0+1
 
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  google_fonts: ^2.1.0
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.9.2
  flash: ^2.0.3+1
  uuid: ^3.0.5
  image_picker: ^0.8.4+11
  flutter_svg: ^1.0.3
  firebase_storage: ^10.2.9
  firebase_crashlytics: ^2.5.3
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.7
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  algolia: ^1.1.1
 
  flutter_localizations:
    sdk: flutter
 
dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true
  assets:
    - .env
 