// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWx92_9RN_PfAtoo8hftqw7rC4Bwx-w9A',
    appId: '1:488478065875:web:51e7231d2d67eb5986c026',
    messagingSenderId: '488478065875',
    projectId: 'fir-flutter-77794',
    authDomain: 'fir-flutter-77794.firebaseapp.com',
    databaseURL: 'https://fir-flutter-77794-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-77794.appspot.com',
    measurementId: 'G-6MTX9EERY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ0yii_ltiQ1-3R_YBta7sbGAd-2njyRM',
    appId: '1:488478065875:android:38a1e34feda4b4be86c026',
    messagingSenderId: '488478065875',
    projectId: 'fir-flutter-77794',
    databaseURL: 'https://fir-flutter-77794-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-77794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGwf695JYvUwwHRrq9tqzxSInxz2hb99g',
    appId: '1:488478065875:ios:ce123167aa98c1ef86c026',
    messagingSenderId: '488478065875',
    projectId: 'fir-flutter-77794',
    databaseURL: 'https://fir-flutter-77794-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-77794.appspot.com',
    iosBundleId: 'com.muskuerade',
  );
}
